# Generated by Django 6.0.1 on 2026-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='Brief summary of the article', max_length=1500),
        ),
    ]
