# Generated by Django 6.0.1 on 2026-01-23 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.store",
            ),
        ),
    ]
