# Generated by Django 6.0.1 on 2026-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tweet_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="tweet_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
